# Generated by Django 2.2.5 on 2019-11-17 22:11

from django.conf import settings
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, unique=True)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ('-position',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255, verbose_name='sity based in')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), srid=4326)),
                ('latitude', models.DecimalField(decimal_places=6, default=1e-06, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=1e-06, max_digits=10)),
                ('claim', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('app_usage', models.BooleanField(default=False, verbose_name='would you love to use the app')),
                ('sex', models.CharField(choices=[('Male', 'm'), ('Female', 'f')], max_length=100)),
                ('sexuality', models.CharField(choices=[('Hetero', 'hetero'), ('Bi', 'bi'), ('Homo', 'homo'), ('Trans', 'trans')], max_length=100, verbose_name='your sexuality')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('figure', models.CharField(choices=[('Thin', 'thin'), ('Slim', 'slim'), ('Feminine', 'feminine'), ('Muscular', 'miscular'), ('Sporty', 'sporty'), ('Easy_going', 'easy_going')], max_length=100)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bust_size', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('D+', 'd+')], max_length=100)),
                ('languages', models.CharField(choices=[('German', 'german'), ('English', 'english'), ('Italian', 'italian')], max_length=100, verbose_name='spoken languages')),
                ('app_language', models.CharField(choices=[('German', 'german'), ('English', 'english'), ('Italian', 'italian')], max_length=100)),
                ('intrests', models.CharField(max_length=100, verbose_name='your intrests')),
                ('best_food', models.CharField(max_length=100)),
                ('drinks', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('dress_style', models.CharField(max_length=100)),
                ('upfront_booking', models.PositiveIntegerField(default=0)),
                ('minimum_booking', models.PositiveIntegerField(default=0)),
                ('custom_travel_from_price', models.PositiveIntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('scent', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('upfront_booking_for_travels', models.PositiveIntegerField(default=0)),
                ('minimum_booking_for_travels', models.PositiveIntegerField(default=0)),
                ('meetup_location', multiselectfield.db.fields.MultiSelectField(choices=[('Home', 'home'), ('Workplace', 'workplace'), ('Hotel', 'hotel')], max_length=100)),
                ('description', models.CharField(max_length=100, verbose_name='brief description')),
                ('booking_notes', models.CharField(max_length=100)),
                ('travel_types', multiselectfield.db.fields.MultiSelectField(choices=[('City', 'city'), ('City Surroundings', 'city_surroundings'), ('National', 'national'), ('International', 'international')], max_length=100)),
                ('adult', models.BooleanField(default=False, verbose_name='are you over 18years of age?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='number of views')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time_from', models.TimeField()),
                ('available_time_to', models.TimeField()),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
